apiVersion: v1
kind: Service
metadata:
  name: {{ include "ops-ui.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ops-ui.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "ops-ui.selectorLabels" . | nindent 4 }}
